// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: consumer_limit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ConsumerLimitService_GetConsumerLimitsByConsumerId_FullMethodName        = "/xyz_grpc.ConsumerLimitService/GetConsumerLimitsByConsumerId"
	ConsumerLimitService_CreateConsumerLimit_FullMethodName                  = "/xyz_grpc.ConsumerLimitService/CreateConsumerLimit"
	ConsumerLimitService_UpdateAvailableLimit_FullMethodName                 = "/xyz_grpc.ConsumerLimitService/UpdateAvailableLimit"
	ConsumerLimitService_GetConsumerLimitByConsumerIdAndTenor_FullMethodName = "/xyz_grpc.ConsumerLimitService/GetConsumerLimitByConsumerIdAndTenor"
)

// ConsumerLimitServiceClient is the client API for ConsumerLimitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerLimitServiceClient interface {
	GetConsumerLimitsByConsumerId(ctx context.Context, in *ConsumerRequest, opts ...grpc.CallOption) (*ConsumerLimitListResponse, error)
	CreateConsumerLimit(ctx context.Context, in *ConsumerLimit, opts ...grpc.CallOption) (*ConsumerLimitResponse, error)
	UpdateAvailableLimit(ctx context.Context, in *UpdateAvailableLimitRequest, opts ...grpc.CallOption) (*ConsumerLimitResponse, error)
	GetConsumerLimitByConsumerIdAndTenor(ctx context.Context, in *ConsumerIdAndTenorRequest, opts ...grpc.CallOption) (*ConsumerLimitResponse, error)
}

type consumerLimitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerLimitServiceClient(cc grpc.ClientConnInterface) ConsumerLimitServiceClient {
	return &consumerLimitServiceClient{cc}
}

func (c *consumerLimitServiceClient) GetConsumerLimitsByConsumerId(ctx context.Context, in *ConsumerRequest, opts ...grpc.CallOption) (*ConsumerLimitListResponse, error) {
	out := new(ConsumerLimitListResponse)
	err := c.cc.Invoke(ctx, ConsumerLimitService_GetConsumerLimitsByConsumerId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerLimitServiceClient) CreateConsumerLimit(ctx context.Context, in *ConsumerLimit, opts ...grpc.CallOption) (*ConsumerLimitResponse, error) {
	out := new(ConsumerLimitResponse)
	err := c.cc.Invoke(ctx, ConsumerLimitService_CreateConsumerLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerLimitServiceClient) UpdateAvailableLimit(ctx context.Context, in *UpdateAvailableLimitRequest, opts ...grpc.CallOption) (*ConsumerLimitResponse, error) {
	out := new(ConsumerLimitResponse)
	err := c.cc.Invoke(ctx, ConsumerLimitService_UpdateAvailableLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerLimitServiceClient) GetConsumerLimitByConsumerIdAndTenor(ctx context.Context, in *ConsumerIdAndTenorRequest, opts ...grpc.CallOption) (*ConsumerLimitResponse, error) {
	out := new(ConsumerLimitResponse)
	err := c.cc.Invoke(ctx, ConsumerLimitService_GetConsumerLimitByConsumerIdAndTenor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerLimitServiceServer is the server API for ConsumerLimitService service.
// All implementations must embed UnimplementedConsumerLimitServiceServer
// for forward compatibility
type ConsumerLimitServiceServer interface {
	GetConsumerLimitsByConsumerId(context.Context, *ConsumerRequest) (*ConsumerLimitListResponse, error)
	CreateConsumerLimit(context.Context, *ConsumerLimit) (*ConsumerLimitResponse, error)
	UpdateAvailableLimit(context.Context, *UpdateAvailableLimitRequest) (*ConsumerLimitResponse, error)
	GetConsumerLimitByConsumerIdAndTenor(context.Context, *ConsumerIdAndTenorRequest) (*ConsumerLimitResponse, error)
	mustEmbedUnimplementedConsumerLimitServiceServer()
}

// UnimplementedConsumerLimitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConsumerLimitServiceServer struct {
}

func (UnimplementedConsumerLimitServiceServer) GetConsumerLimitsByConsumerId(context.Context, *ConsumerRequest) (*ConsumerLimitListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerLimitsByConsumerId not implemented")
}
func (UnimplementedConsumerLimitServiceServer) CreateConsumerLimit(context.Context, *ConsumerLimit) (*ConsumerLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsumerLimit not implemented")
}
func (UnimplementedConsumerLimitServiceServer) UpdateAvailableLimit(context.Context, *UpdateAvailableLimitRequest) (*ConsumerLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAvailableLimit not implemented")
}
func (UnimplementedConsumerLimitServiceServer) GetConsumerLimitByConsumerIdAndTenor(context.Context, *ConsumerIdAndTenorRequest) (*ConsumerLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerLimitByConsumerIdAndTenor not implemented")
}
func (UnimplementedConsumerLimitServiceServer) mustEmbedUnimplementedConsumerLimitServiceServer() {}

// UnsafeConsumerLimitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerLimitServiceServer will
// result in compilation errors.
type UnsafeConsumerLimitServiceServer interface {
	mustEmbedUnimplementedConsumerLimitServiceServer()
}

func RegisterConsumerLimitServiceServer(s grpc.ServiceRegistrar, srv ConsumerLimitServiceServer) {
	s.RegisterService(&ConsumerLimitService_ServiceDesc, srv)
}

func _ConsumerLimitService_GetConsumerLimitsByConsumerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerLimitServiceServer).GetConsumerLimitsByConsumerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerLimitService_GetConsumerLimitsByConsumerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerLimitServiceServer).GetConsumerLimitsByConsumerId(ctx, req.(*ConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerLimitService_CreateConsumerLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerLimit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerLimitServiceServer).CreateConsumerLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerLimitService_CreateConsumerLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerLimitServiceServer).CreateConsumerLimit(ctx, req.(*ConsumerLimit))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerLimitService_UpdateAvailableLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvailableLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerLimitServiceServer).UpdateAvailableLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerLimitService_UpdateAvailableLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerLimitServiceServer).UpdateAvailableLimit(ctx, req.(*UpdateAvailableLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerLimitService_GetConsumerLimitByConsumerIdAndTenor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerIdAndTenorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerLimitServiceServer).GetConsumerLimitByConsumerIdAndTenor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerLimitService_GetConsumerLimitByConsumerIdAndTenor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerLimitServiceServer).GetConsumerLimitByConsumerIdAndTenor(ctx, req.(*ConsumerIdAndTenorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsumerLimitService_ServiceDesc is the grpc.ServiceDesc for ConsumerLimitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerLimitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz_grpc.ConsumerLimitService",
	HandlerType: (*ConsumerLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConsumerLimitsByConsumerId",
			Handler:    _ConsumerLimitService_GetConsumerLimitsByConsumerId_Handler,
		},
		{
			MethodName: "CreateConsumerLimit",
			Handler:    _ConsumerLimitService_CreateConsumerLimit_Handler,
		},
		{
			MethodName: "UpdateAvailableLimit",
			Handler:    _ConsumerLimitService_UpdateAvailableLimit_Handler,
		},
		{
			MethodName: "GetConsumerLimitByConsumerIdAndTenor",
			Handler:    _ConsumerLimitService_GetConsumerLimitByConsumerIdAndTenor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consumer_limit.proto",
}
